export const GENERATE_RANDOM_RECIPES = 'GENERATE_RANDOM_RECIPES';
export const SEARCH_RECIPES = 'SEARCH_RECIPES';
export const GET_RECIPE_DETAIL = 'GET_RECIPE_DETAIL';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

export const REMOVE_TO_FAVORITES = 'REMOVE_TO_FAVORITES';